### ISSUE TITLE
书籍元数据重复

### ISSUE THREAD

**Issue by MOxFIVE** [talebook/talebook-library#1]
《喧哗与骚动》元数据被用于其他多本书籍，可更正。
--------------------------
![2acc40f3-938b-4530-9c68-d151a4f6f397](https://cloud.githubusercontent.com/assets/10032927/5729064/596713b4-9baa-11e4-8bec-749844abe650.png)

**Comment by talebook** [comment]
谢谢反馈。正在修正。

**Comment by talebook** [comment]
修正了。
